### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when using 

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/pulumi-kubernetes#2093]
### What happened?

Using the `k8s.yaml.ConfigFile` resource crashes during `pulumi up`.

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/alex/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/home/alex/.pulumi/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib64/python3.9/runpy.py", line 288, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "pulumi_main.py", line 27, in <module>
        from infra import regions as _
      File "/home/alex/git2/cloud/./infra/regions.py", line 166, in <module>
        Region(
      File "/home/alex/git2/cloud/./infra/regions.py", line 127, in __init__
        CertManager(cluster, cluster_dns_zone.provision_zone)
      File "/home/alex/git2/cloud/./infra/tls.py", line 40, in __init__
        self.crds = k8s.yaml.ConfigFile(
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi_kubernetes/yaml/yaml.py", line 380, in __init__
        __ret__ = invoked.value["result"]
    TypeError: 'NoneType' object is not subscriptable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Steps to reproduce

The following code triggers it when using pulumi-kubernetes 3.20.0 or 3.20.1:
```python3
self.crds = k8s.yaml.ConfigFile(
    "cert-manager-crds",
    file="https://github.com/jetstack/cert-manager/releases/download/v1.8.1/cert-manager.crds.yaml",
    opts=pulumi.ResourceOptions(
        parent=self,
        provider=cluster.provider,
    ),
)
```

Note that this does not happen if the resource is initially created with an older version (confirmed with 3.19.1) and then upgraded to the new provider.

### Expected Behavior

Pulumi should create the resources defined in the yaml file in the kubernetes cluster specified by the provider in the ResourceOptions.

### Actual Behavior

Pulumi crashes in the preview.

### Versions used

```
CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME              VERSION
aws               5.9.1
cloudinit         1.3.0
command           0.2.0
docker-buildkit   0.1.17
eks               0.40.0
fivetran          0.1.6
frontegg          0.2.22
honeycomb         0.0.11
kubernetes        3.20.0
kubernetes-proxy  0.1.3
linkerd-link      0.0.7
postgresql        3.5.0
postgresql-exec   0.1.1
python            unknown
random            4.7.0
tls               4.6.0

Host     
OS       fedora
Version  35
Arch     x86_64

This project is written in python: executable='/home/alex/git3/cloud/venv/bin/python3' version='3.9.13'

{{Stack output redacted because it's huge.}}

Dependencies:
NAME                                 VERSION
analytics-python                     1.4.0
black                                22.6.0
boto3                                1.24.26
boto3-stubs                          1.24.26
cryptography-347-stubs               1.0.0
dj-database-url                      0.5.0
django-csp                           3.7
django-migrations-formatter          1.0.0
django-proxy                         1.2.1
django-ratelimit                     3.0.1
django-simple-history                3.1.1
django-types                         0.15.0
djangorestframework-camel-case       1.3.0
djangorestframework-types            0.7.0
docker-image-py                      0.1.12
drf-spectacular                      0.22.1
gunicorn                             20.1.0
honeycomb-stubs                      0.2.2
isort                                5.10.1
jwcrypto                             1.3.1
kubernetes                           21.7.0
kubernetes-stubs                     21.7.0
mypy-boto3-ec2                       1.24.32
mypy-boto3-elb                       1.24.0
mypy-boto3-elbv2                     1.24.20.post14
mypy-boto3-resourcegroupstaggingapi  1.24.0
mypy-boto3-route53                   1.24.1
mypy-boto3-s3                        1.24.0
mypy-boto3-sts                       1.24.0
oauth2client                         4.1.3
pip                                  22.1.2
pre-commit                           2.19.0
psycopg2                             2.9.3
pulumi-cloudinit                     1.3.0
pulumi-command                       0.2.0
pulumi-docker-buildkit               0.1.17
pulumi-eks                           0.40.0
pulumi-fivetran                      0.1.6
pulumi-frontegg                      0.2.22
pulumi-honeycomb                     0.0.11
pulumi-kubernetes-proxy              0.1.3
pulumi-linkerd-link                  0.0.7
pulumi-postgresql                    3.5.0
pulumi-postgresql-exec               0.1.1
pulumi-random                        4.7.0
pulumi-tls                           4.6.0
pydantic                             1.9.1
pyOpenSSL                            22.0.0
python-json-logger                   2.0.2
pytz                                 2022.1
sentry-sdk                           1.5.12
slack-sdk                            3.16.2
timeout-decorator                    0.5.0
types-cachetools                     5.2.1
types-pyOpenSSL                      22.0.3
wheel                                0.37.1
whitenoise                           6.2.0
```

### Additional context

This seems very similar (possible duplicate?) to https://github.com/pulumi/pulumi-kubernetes/issues/2038 , but that one is in typescript, so it's hard to tell.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
@alex-hunt-materialize Are you able to confirm that at the point of the failure above if the kubernetes cluster corresponding to the k8s provider being passed (cluster.provider) is actually up? If not this is a duplicate of https://github.com/pulumi/pulumi-kubernetes/issues/2038

**Comment by alex-hunt-materialize** [comment]
The cluster is definitely up, and is reachable even to create other resources using that provider.

**Comment by terrafying** [comment]
I have the same issue, where kustomize Directory() didn't appear to respect the ResourceOptions, complaining that the default 'kubernetes' provider is missing, even though I've specified a provider.  After tinkering with that, had the same error as the first post.  Also, setting a Directory as a dependency of something else fails.

**Comment by jaxxstorm** [comment]
To repro:

- create a Kubernetes cluster
- Then install a yaml file

make these separate operations to repro. If the resource exists in the state, and you upgrade the provider this does not repro

Will break again if you upgrade the CLI.

**Comment by danylo-omelchenko** [comment]
Hi, seems like I'm having trouble with it too. 
Same code was working for version 3.19.1. After update to 3.20.2 it crashes with:
```
.../site-packages/pulumi_kubernetes/yaml/yaml.py", line 348, in __init__
        __ret__ = pulumi.runtime.invoke('kubernetes:yaml:decode', {'text': text}, invoke_opts).[secret].get('result')
    AttributeError: 'NoneType' object has no attribute 'get'
```


code:
```python
k8s.yaml.ConfigFile(
          'knative-operator',
          file=pulumi_knative.info.ULR,
          transformations=[add_node_selector(install_on.get_system_node_pool_selector())],
          opts=pulumi.ResourceOptions(
              parent=self,
              provider=opts.provider))
```

**Comment by lblackstone** [comment]
It seems like this might be related to the version of the `protobuf` library that was recently updated in https://github.com/pulumi/pulumi/pull/10063

I had an older virtualenv on my machine, and did not get the same error with the latest `pulumi-kubernetes` package. However, I was hitting the issue with the very slow CRD performance, so I upgraded the `pulumi` package and see the same error now.

```
protobuf==4.21.4
pulumi==3.37.1
```

**Comment by viveklak** [comment]
Could we confirm if this is only happening in python?

**Comment by lblackstone** [comment]
> Could we confirm if this is only happening in python?

I just tested with NodeJS, and it works fine with the same versions of `pulumi` and `pulumi-kubernetes`.

**Comment by lblackstone** [comment]
I added some additional logging while testing locally and got the following:
```
<_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.INTERNAL
    	details = "Exception deserializing response!"
    	debug_error_string = "None"
    >
    invoke of kubernetes:yaml:decode failed: Exception deserializing response!
```

This appears to be an issue with the gRPC layer in Python. I wasn't seeing the same error if I set `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`, but the update never completed in that case.
