### ISSUE TITLE
ctrl-c orphans resources or doesn't register init error

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#252]
This was resolved by #251. From the commit message:

> InitializationError is used to signal to the provider that a resource
> has successfully been created, but not initialized. Currently
> cancellationError does not implement this interface, so if
> Deployment or Service are cancelled, this is not registered as a
> partial failure with the engine or service.
> 
> This did not used to be the case, but was a regression with #236.
> 
> We already have good tests to make sure that Deployment and Service return the appropriate cancellation and timeout errors under various circumstances -- it's not clear that additional tests would help here, as the problem is that the error implementations didn't technically implement the correct interface. As a safeguard against this in the future I've added a sentinel check var _ InitializationError = (*cancellationError)(nil), which should cause the compiler to error out on regression.

**Comment by hausdorff** [comment]
This was initialized in v0.17.2 and fixed in v0.17.3.
