### ISSUE TITLE
ComponentResource parenting failure

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-kubernetes#148]
Switched to version `0.15.1`. I have lots of `ComponentResource`s that worked with `0.14.x` but now they all error with something like: 

```
lib/prisma.ts:105:7 - error TS2345: Argument of type '{ parent: this; }' is not assignable to parameter of type 'CustomResourceOptions | undefined'.
  Type '{ parent: this; }' is not assignable to type 'CustomResourceOptions'.
    Types of property 'parent' are incompatible.
      Type 'this' is not assignable to type 'Resource | undefined'.
        Type 'this' is not assignable to type 'Resource'.

105       { parent: this }
          ~~~~~~~~~~~~~~~~
```

I'll try to follow up with a test case.

**Comment by hausdorff** [comment]
Hmm, it's hard to say what's going on here. `ComponentResource` extends `Resource`, so if `this` is a `ComponentResource`, this seems like it should work. Can you provide more detail?

**Comment by joeduffy** [comment]
Also cc @CyrusNajmabadi as he tends to be a typing wizard.

**Comment by CyrusNajmabadi** [comment]
Would need to see a bit more of the typings to get what is happening here.  

Note: one thing that may be biting @protometa is mismatched versions of our libraries.  i.e. they have @pulumi/pulumi pulled in through multiple paths.  And through one path things have a slightly different shape.  I'm a bit confused by teh error too if it also ends with:

```
        Type 'this' is not assignable to type 'Resource'.

105       { parent: this }
          ~~~~~~~~~~~~~~~
```

Normally TS is good about telling you *why* it's not assignable.  Since htis is all a structural type system, it normally gives you what part of the structure is invalid.  

@protometa was there any additional info given in the error message?  Thanks!

**Comment by protometa** [comment]
Yeah I updated my `@pulumi/pulumi` version and that fixed things. Should there be a peerDependency warning?

**Comment by protometa** [comment]
Oh I see that `@pulumi/pulumi` is a real dependency. Perhaps it's a major version 0 semver failure.

**Comment by protometa** [comment]
Actually I guess it's just about using a `@pulumi/pulumi@0.14.x` `ComponentResource` with a `@pulumi/kubernetes@0.15.x` child resource. Maybe listing a peer dependency is the way to go.

**Comment by protometa** [comment]
After upgrading I'm getting a new error though #1820

**Comment by hausdorff** [comment]
@CyrusNajmabadi you know more about node stuff than I do... do you think it should be listed as a peer dependency?
